ALTER TABLE model_versions
    ADD COLUMN IF NOT EXISTS artifact_digest TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS artifact_size BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS storage_type TEXT NOT NULL DEFAULT 's3',
    ADD COLUMN IF NOT EXISTS artifact_verified_at TIMESTAMPTZ;
