ALTER TABLE deployments
    ADD COLUMN IF NOT EXISTS stable_endpoint TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS canary_endpoint TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS rollout_status TEXT NOT NULL DEFAULT '';

ALTER TABLE gateway_routes
    ADD COLUMN IF NOT EXISTS stable_endpoint TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS canary_endpoint TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS rollout_status TEXT NOT NULL DEFAULT '';
